# Generated by Django 3.2 on 2023-05-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='change_1h',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='change_24h',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='change_7d',
            field=models.CharField(max_length=10),
        ),
    ]
