# Generated by Django 3.2 on 2023-05-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_auto_20230511_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='circulating_supply',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='market_cap',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='price',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='volume',
            field=models.CharField(max_length=30),
        ),
    ]
