# Generated by Django 3.2 on 2023-05-12 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_auto_20230511_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='PercentageChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_1h', models.CharField(max_length=10)),
                ('change_24h', models.CharField(max_length=10)),
                ('change_7d', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='change_1h',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='change_24h',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='change_7d',
        ),
        migrations.AddField(
            model_name='crypto',
            name='percent_change',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='crypto.percentagechange'),
            preserve_default=False,
        ),
    ]
