# Generated by Django 3.2 on 2023-05-12 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_auto_20230512_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='percent_change',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto.percentagechange'),
        ),
    ]
